// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAejLhYFUKKAutbM5-eymV5d1aXU6osDBs',
    appId: '1:593891015650:web:af214852304bf541d297bb',
    messagingSenderId: '593891015650',
    projectId: 'montraexpense-aa953',
    authDomain: 'montraexpense-aa953.firebaseapp.com',
    storageBucket: 'montraexpense-aa953.appspot.com',
    measurementId: 'G-BTFJPED07W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAkND6IJpseyA6r5jw4JUf86KcjwPdnrQ',
    appId: '1:593891015650:android:18ff174dc4237bdad297bb',
    messagingSenderId: '593891015650',
    projectId: 'montraexpense-aa953',
    storageBucket: 'montraexpense-aa953.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYdokmg1PVaiRiPgxQqmnnZyefGNTZ2DM',
    appId: '1:593891015650:ios:6c6f329b3e95205cd297bb',
    messagingSenderId: '593891015650',
    projectId: 'montraexpense-aa953',
    storageBucket: 'montraexpense-aa953.appspot.com',
    iosBundleId: 'com.example.montraExpenseTracker',
  );
}
